### ISSUE TITLE
I am getting this error when trying rainbowkit integration with zerodev wagmi 

### ISSUE THREAD

**Issue by GouthamJM** [zerodevapp/zerodev-wagmi#11]
![Screenshot 2023-11-09 at 12 10 20 PM](https://github.com/zerodevapp/zerodev-wagmi/assets/67677902/3db2674a-92f5-4d82-9c16-3b2b3b482121)

```
 error Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/designstring/Desktop/projects/nextjs/stabl/node_modules/.pnpm/wagmi@1.4.6_react-dom@18.2.0_react@18.2.0_typescript@5.2.2_viem@1.18.9/node_modules/wagmi/dist/index.js from /Users/designstring/Desktop/projects/nextjs/stabl/node_modules/.pnpm/@zerodev+wagmi@4.1.21_@babel+runtime@7.23.2_@privy-io+react-auth@1.46.1_@privy-io+wagmi-conne_ecg32oxmrlqrkwllnvfdogekhy/node_modules/@zerodev/wagmi/dist/cjs/connectors/ZeroDevConnector.js not supported.
Instead change the require of index.js in /Users/designstring/Desktop/projects/nextjs/stabl/node_modules/.pnpm/@zerodev+wagmi@4.1.21_@babel+runtime@7.23.2_@privy-io+react-auth@1.46.1_@privy-io+wagmi-conne_ecg32oxmrlqrkwllnvfdogekhy/node_modules/@zerodev/wagmi/dist/cjs/connectors/ZeroDevConnector.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/designstring/Desktop/projects/nextjs/stabl/node_modules/.pnpm/@zerodev+wagmi@4.1.21_@babel+runtime@7.23.2_@privy-io+react-auth@1.46.1_@privy-io+wagmi-conne_ecg32oxmrlqrkwllnvfdogekhy/node_modules/@zerodev/wagmi/dist/cjs/connectors/ZeroDevConnector.js:4:17)
    at Object.<anonymous> (/Users/designstring/Desktop/projects/nextjs/stabl/node_modules/.pnpm/@zerodev+wagmi@4.1.21_@babel+runtime@7.23.2_@privy-io+react-auth@1.46.1_@privy-io+wagmi-conne_ecg32oxmrlqrkwllnvfdogekhy/node_modules/@zerodev/wagmi/dist/cjs/connectors/AbstractWeb3AuthWalletConnector.js:4:31)
    at Object.<anonymous> (/Users/designstring/Desktop/projects/nextjs/stabl/node_modules/.pnpm/@zerodev+wagmi@4.1.21_@babel+runtime@7.23.2_@privy-io+react-auth@1.46.1_@privy-io+wagmi-conne_ecg32oxmrlqrkwllnvfdogekhy/node_modules/@zerodev/wagmi/dist/cjs/connectors/GoogleSocialWalletConnector.js:4:46)
    at Object.<anonymous> (/Users/designstring/Desktop/projects/nextjs/stabl/node_modules/.pnpm/@zerodev+wagmi@4.1.21_@babel+runtime@7.23.2_@privy-io+react-auth@1.46.1_@privy-io+wagmi-conne_ecg32oxmrlqrkwllnvfdogekhy/node_modules/@zerodev/wagmi/dist/cjs/integrations/rainbowkit/wallets/googleWallet.js:4:42)
    at Object.<anonymous> (/Users/designstring/Desktop/projects/nextjs/stabl/node_modules/.pnpm/@zerodev+wagmi@4.1.21_@babel+runtime@7.23.2_@privy-io+react-auth@1.46.1_@privy-io+wagmi-conne_ecg32oxmrlqrkwllnvfdogekhy/node_modules/@zerodev/wagmi/dist/cjs/integrations/rainbowkit/wallets/index.js:4:25)
    at Object.<anonymous> (/Users/designstring/Desktop/projects/nextjs/stabl/node_modules/.pnpm/@zerodev+wagmi@4.1.21_@babel+runtime@7.23.2_@privy-io+react-auth@1.46.1_@privy-io+wagmi-conne_ecg32oxmrlqrkwllnvfdogekhy/node_modules/@zerodev/wagmi/dist/cjs/integrations/rainbowkit/index.js:18:14)
    at Object.@zerodev/wagmi/rainbowkit (/Users/designstring/Desktop/projects/nextjs/stabl/.next/server/pages/index.js:184:18)
    at __webpack_require__ (/Users/designstring/Desktop/projects/nextjs/stabl/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/ZeroDevWrapper.js:15:83)
    at Function.__webpack_require__.a (/Users/designstring/Desktop/projects/nextjs/stabl/.next/server/webpack-runtime.js:97:13)
    at eval (webpack-internal:///./pages/ZeroDevWrapper.js:1:21)
    at Object../pages/ZeroDevWrapper.js (/Users/designstring/Desktop/projects/nextjs/stabl/.next/server/pages/index.js:65:1)
    at __webpack_require__ (/Users/designstring/Desktop/projects/nextjs/stabl/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/index.js:10:73)
    at Function.__webpack_require__.a (/Users/designstring/Desktop/projects/nextjs/stabl/.next/server/webpack-runtime.js:97:13)
    at eval (webpack-internal:///./pages/index.js:1:21)
    at Object../pages/index.js (/Users/designstring/Desktop/projects/nextjs/stabl/.next/server/pages/index.js:98:1)
    at __webpack_require__ (/Users/designstring/Desktop/projects/nextjs/stabl/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./node_modules/.pnpm/next@13.4.11_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/webpack/loaders/next-route-loader/index.js?page=%2F&preferredRegion=&absolutePagePath=.%2Fpages%2Findex.js&absoluteAppPath=private-next-pages%2F_app&absoluteDocumentPath=private-next-pages%2F_document&middlewareConfigBase64=e30%3D!:22:73)
    at Function.__webpack_require__.a (/Users/designstring/Desktop/projects/nextjs/stabl/.next/server/webpack-runtime.js:97:13)
    at eval (webpack-internal:///./node_modules/.pnpm/next@13.4.11_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/webpack/loaders/next-route-loader/index.js?page=%2F&preferredRegion=&absolutePagePath=.%2Fpages%2Findex.js&absoluteAppPath=private-next-pages%2F_app&absoluteDocumentPath=private-next-pages%2F_document&middlewareConfigBase64=e30%3D!:1:21)
    at Object../node_modules/.pnpm/next@13.4.11_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/webpack/loaders/next-route-loader/index.js?page=%2F&preferredRegion=&absolutePagePath=.%2Fpages%2Findex.js&absoluteAppPath=private-next-pages%2F_app&absoluteDocumentPath=private-next-pages%2F_document&middlewareConfigBase64=e30%3D! (/Users/designstring/Desktop/projects/nextjs/stabl/.next/server/pages/index.js:43:1)
    at __webpack_require__ (/Users/designstring/Desktop/projects/nextjs/stabl/.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (/Users/designstring/Desktop/projects/nextjs/stabl/.next/server/pages/index.js:337:39)
    at /Users/designstring/Desktop/projects/nextjs/stabl/.next/server/pages/index.js:338:28
    at Object.<anonymous> (/Users/designstring/Desktop/projects/nextjs/stabl/.next/server/pages/index.js:341:3)
    at requirePage (/Users/designstring/Desktop/projects/nextjs/stabl/node_modules/.pnpm/next@13.4.11_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/require.js:112:75)
    at /Users/designstring/Desktop/projects/nextjs/stabl/node_modules/.pnpm/next@13.4.11_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/load-components.js:80:84
    at async loadComponentsImpl (/Users/designstring/Desktop/projects/nextjs/stabl/node_modules/.pnpm/next@13.4.11_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/load-components.js:80:26)
    at async DevServer.findPageComponentsImpl (/Users/designstring/Desktop/projects/nextjs/stabl/node_modules/.pnpm/next@13.4.11_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:772:36)
    at async DevServer.findPageComponents (/Users/designstring/Desktop/projects/nextjs/stabl/node_modules/.pnpm/next@13.4.11_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/dev/next-dev-server.js:1271:20)
    at async DevServer.renderPageComponent (/Users/designstring/Desktop/projects/nextjs/stabl/node_modules/.pnpm/next@13.4.11_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:1357:24)
    at async DevServer.renderToResponseImpl (/Users/designstring/Desktop/projects/nextjs/stabl/node_modules/.pnpm/next@13.4.11_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:1401:32)
    at async DevServer.pipeImpl (/Users/designstring/Desktop/projects/nextjs/stabl/node_modules/.pnpm/next@13.4.11_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:645:25)
    at async Object.fn (/Users/designstring/Desktop/projects/nextjs/stabl/node_modules/.pnpm/next@13.4.11_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:1153:21)
    at async Router.execute (/Users/designstring/Desktop/projects/nextjs/stabl/node_modules/.pnpm/next@13.4.11_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/router.js:315:32)
    at async DevServer.runImpl (/Users/designstring/Desktop/projects/nextjs/stabl/node_modules/.pnpm/next@13.4.11_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:619:29)
    at async DevServer.run (/Users/designstring/Desktop/projects/nextjs/stabl/node_modules/.pnpm/next@13.4.11_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/dev/next-dev-server.js:910:20)
    at async DevServer.handleRequestImpl (/Users/designstring/Desktop/projects/nextjs/stabl/node_modules/.pnpm/next@13.4.11_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:546:20) {
  digest: undefined
}
```

**Comment by camdengrieh** [comment]
Any updates on this? I'm facing the same problem
